# hoisting behavior
hoist: true
shamefullyHoist: true

# dependency behavior
dedupeDirectDeps: true
ignoreWorkspaceRootCheck: true
shellEmulator: true


minimumReleaseAge: 0
trustPolicyExclude:
  - semver # Excludes all versions
allowBuilds:
  unrs-resolver: false
